//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftHelper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DraftHelperEntities : DbContext
    {
        public DraftHelperEntities()
            : base("name=DraftHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NFLPlayer> NFLPlayers { get; set; }
        public DbSet<NFLTeam> NFLTeams { get; set; }
        public DbSet<TeamOwner> TeamOwners { get; set; }
        public DbSet<DraftPick> DraftPicks { get; set; }
    }
}
