//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftPick
    {
        public int Id { get; set; }
        public int PickNumber { get; set; }
    
        public virtual TeamOwner TeamOwner { get; set; }
        public virtual NFLPlayer SelectedPlayer { get; set; }
    }
}
