//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLTeam
    {
        public NFLTeam()
        {
            this.NFLPlayers = new HashSet<NFLPlayer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Locale { get; set; }
        public string Abbrev { get; set; }
        public string Conference { get; set; }
        public string Division { get; set; }
    
        public virtual ICollection<NFLPlayer> NFLPlayers { get; set; }
    }
}
