//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamOwner
    {
        public TeamOwner()
        {
            this.DraftPicks = new HashSet<DraftPick>();
        }
    
        public int Id { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> DraftOrder { get; set; }
    
        public virtual ICollection<DraftPick> DraftPicks { get; set; }
    }
}
